/**
 * Business Domain Constants
 * Based on BIZ_DOMAIN.md
 */

export interface BizDomainInfo {
  name: string;
  displayName: string;
  description: string;
  icon: string;
  category: 'core' | 'support' | 'common';
}

/**
 * All Business Domains (11 total)
 * - Core Servicing Domains (5)
 * - Support Domain Capabilities (5)
 * - General Domain Capabilities (1)
 */
export const BIZ_DOMAINS: BizDomainInfo[] = [
  // Core Servicing Domains (5)
  {
    name: 'CLAIM',
    displayName: 'Claim',
    description: 'Manages all customer requests arising from an insured event, fulfilling the core promise of the insurance contract.',
    icon: '📋',
    category: 'core',
  },
  {
    name: 'FINANCIAL_CHANGE',
    displayName: 'Financial Change',
    description: 'Handles changes related to the financial attributes of a policy, focusing on policy maintenance, corrections, and status.',
    icon: '💰',
    category: 'core',
  },
  {
    name: 'INQUIRY_GENERAL_CHANGES',
    displayName: 'Inquiry & General Changes',
    description: 'Responds to routine customer queries and processes non-financial updates to policyholder information.',
    icon: '❓',
    category: 'core',
  },
  {
    name: 'MONEY_OUT',
    displayName: 'Money Out (Value Withdrawal)',
    description: 'Processes all non-claim related fund withdrawals initiated by the customer or as scheduled by the contract.',
    icon: '💸',
    category: 'core',
  },
  {
    name: 'WEALTH',
    displayName: 'Wealth',
    description: 'Provides specialized services related to investment-linked or wealth management products (e.g., ILP, Universal Life).',
    icon: '📈',
    category: 'core',
  },
  // Support Domain Capabilities (5)
  {
    name: 'CUSTOMER_ENGAGEMENT',
    displayName: 'Customer Engagement',
    description: 'Ensures a consistent, seamless, and personalized service experience across all customer touchpoints and manages proactive customer communications.',
    icon: '💬',
    category: 'support',
  },
  {
    name: 'CUSTOMER_RELATIONSHIP_MANAGEMENT',
    displayName: 'Customer & Relationship Management',
    description: 'Manages the master data and single source of truth for customer information, enabling personalized service delivery.',
    icon: '👥',
    category: 'support',
  },
  {
    name: 'PAYMENT_SETTLEMENT',
    displayName: 'Payment & Settlement',
    description: 'Provides the underlying infrastructure for all fund movements (inflows and outflows) supporting business processes.',
    icon: '💳',
    category: 'support',
  },
  {
    name: 'FINANCE_ACCOUNTING',
    displayName: 'Finance & Accounting',
    description: 'Manages all financial bookkeeping, reconciliation, and settlement generated by service activities to ensure accuracy.',
    icon: '📊',
    category: 'support',
  },
  {
    name: 'RISK_COMPLIANCE',
    displayName: 'Risk & Compliance',
    description: 'Ensures all service processes adhere to regulatory requirements (Regulatory) and internal risk controls (Risk).',
    icon: '🛡️',
    category: 'support',
  },
  // General Domain Capabilities (1)
  {
    name: 'COMMON_CAPABILITIES',
    displayName: 'Common Capabilities',
    description: 'Provides shared infrastructure, data management, identity services, and document management capabilities that enable all business and support domains to operate effectively.',
    icon: '🔧',
    category: 'common',
  },
];

/**
 * Business Domain lookup by name
 */
export const BIZ_DOMAIN_MAP: Record<string, BizDomainInfo> = BIZ_DOMAINS.reduce(
  (acc, domain) => {
    acc[domain.name] = domain;
    return acc;
  },
  {} as Record<string, BizDomainInfo>
);

/**
 * Core Servicing Domains only
 */
export const CORE_BIZ_DOMAINS = BIZ_DOMAINS.filter((d) => d.category === 'core');

/**
 * Support Domain Capabilities only
 */
export const SUPPORT_BIZ_DOMAINS = BIZ_DOMAINS.filter((d) => d.category === 'support');

/**
 * Common Capabilities only
 */
export const COMMON_BIZ_DOMAINS = BIZ_DOMAINS.filter((d) => d.category === 'common');

/**
 * Horizontal Capabilities only (deprecated, use SUPPORT_BIZ_DOMAINS instead)
 * Kept for backward compatibility
 */
export const HORIZONTAL_BIZ_DOMAINS = SUPPORT_BIZ_DOMAINS;

/**
 * Get business domain info by name
 */
export function getBizDomainInfo(name: string): BizDomainInfo | undefined {
  return BIZ_DOMAIN_MAP[name];
}

/**
 * Get all business domain names
 */
export function getAllBizDomainNames(): string[] {
  return BIZ_DOMAINS.map((d) => d.name);
}

/**
 * Get business domain display name
 */
export function getBizDomainDisplayName(name: string): string {
  return BIZ_DOMAIN_MAP[name]?.displayName || name;
}

/**
 * Get business domain icon
 */
export function getBizDomainIcon(name: string): string {
  return BIZ_DOMAIN_MAP[name]?.icon || '📦';
}

